CC=g++

1:
	mkdir -p bin
	$(CC) firstprogram.cpp -o bin/firstprogram

2:
	mkdir -p bin
	$(CC) functionprototyping.cpp -o bin/functionprototyping

3:
	mkdir -p bin
	$(CC) giveerror.cpp -o bin/giveerror

4:
	mkdir -p bin
	$(CC) functions.cpp -o bin/functions
