#pragma once

#define LEXER_TOKEN_BUFFER 16 // 16 bytes


enum Keyword {
    KEYWORD_ILLEGAL,
    KEYWORD_AND,
    KEYWORD_BREAK,
    KEYWORD_DO,
    KEYWORD_ELSE,
    KEYWORD_ELSEIF,
    KEYWORD_END,
    KEYWORD_FALSE,
    KEYWORD_FOR,
    KEYWORD_FUNCTION,
    KEYWORD_MAIN,
    KEYWORD_IF,
    KEYWORD_IN,
    KEYWORD_LOCAL,
    KEYWORD_NIL,
    KEYWORD_NOT,
    KEYWORD_OR,
    KEYWORD_REPEAT,
    KEYWORD_RETURN,
    KEYWORD_THEN,
    KEYWORD_TRUE,
    KEYWORD_UNTIL,
    KEYWORD_WHILE,
};

enum TokenType {
    TOK_ILLEGAL,
    TOK_KEYWORD,
    TOK_IDENTIFIER,
    TOK_NUMVAL,
};
